# AMCL localization
min_particles: 100
max_particles: 2000
laser_model_type: likelihood_field
laser_max_beams: 60
update_min_d: 0.2
update_min_a: 0.2
odom_model_type: diff
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2
resample_interval: 1
transform_tolerance: 1.0
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0
gui_publish_rate: 10.0
laser_max_range: 12.0
laser_min_range: 0.1
